name = "DomainColoring"
uuid = "c24f3079-adb7-4533-8329-9f66732e5e85"
authors = ["Evert Provoost <evert@eprovst.net>"]
version = "2.0.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"

[weakdeps]
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
MakieExt = "MakieCore"
PlotsExt = "Plots"

[compat]
Colors = "0.13"
ColorSchemes = "3"
MakieCore = "0.8, 0.9"
Plots = "1"
julia = "1.9"
