name = "DomainColoring"
uuid = "c24f3079-adb7-4533-8329-9f66732e5e85"
authors = ["Evert Provoost <evert@eprovst.net>"]
version = "0.1.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"

[compat]
ColorTypes = "0.11"
MakieCore = "0.6"
julia = "1.6"
