name = "GLDomainColoring"
uuid = "7cf40ad8-af6a-4ede-b3c6-2a9df3bce851"
authors = ["Evert Provoost <evert@eprovst.net>"]
version = "0.1.0"

[deps]
DomainColoring = "c24f3079-adb7-4533-8329-9f66732e5e85"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
